### ISSUE TITLE
Malformed UTF-8 data

### ISSUE THREAD

**Issue by wenytang-ms** [controlplaneio/research-vscode#9]
you really did a great job!
but while i tried this extension on several platform, the extension meet same error "Malformed UTF-8 data" and failed
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
0. F5 to start local debug
1. trigger command palette
2. "steal credential'
3. "find secrets"

**Expected behaviour**

**Screenshots**
![image](https://github.com/controlplaneio/research-vscode/assets/75360946/b7beb4c4-cbb0-4cd4-8932-e0e749332871)

```
Found password in keyring: 
extensionHostProcess.js:148
------------------------
extensionHostProcess.js:148
DECRYPTING SECRETS
extensionHostProcess.js:148
------------------------
extensionHostProcess.js:148
Decrypting entry for: secret://{"extensionId":"vscode.microsoft-authentication","key":"microsoft.login.keylist"}
extensionHostProcess.js:148
Base64 encrypted secret:  ***************
```
**Additional context**

**Comment by yetsmarch-sina** [comment]
sorry for this issue, once setup the secret-tool, it works fine. 
so close this issue.

**Comment by wenytang-ms** [comment]
sorry about this issue, once setup the key-ring, this extension work fine. 
so close this issue, it really a good job!
